### PR TITLE
Fix of out of bound remove index in flatten

### PR DESCRIPTION
**Pull request by martin-kolarik**
Solves #79.

### CODE REVIEW

**Comment by martin-kolarik** [comment]
Solves #81.

**Comment by Pauan** [comment]
Nice catch, though I think a better solution is to just reverse the `RemoveAt`, since that's more efficient.

**Comment by martin-kolarik** [comment]
Exactly, I was considering it, but then I chose "less changes".

**Comment by Pauan** [comment]
Sorry for the delay, I decided to go with the `rev()` implementation instead. Thanks for the report!

**Pull request closed without merging**
